language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install:
    - pip install codecov
script:
  - pytest
  - coverage run --source needystates setup.py test

after_success:
  - codecov